### PR TITLE
add SEPARATE_ASM_MODULE_NAME

### PR DESCRIPTION
**Pull request by italocoin-project**
This fixes issue https://github.com/mymonero/mymonero-core-js/issues/96

### CODE REVIEW

**Comment by paulshapiro** [comment]
Thanks for the PR! Has this been tested under ASMJS?

**Comment by italocoin-project** [comment]
No problem, tested on both, if you can re-test and confirm that would be great.

**Comment by paulshapiro** [comment]
Yup. Ah, one last thing, can you retarget this PR to the branch `develop`?

**Comment by italocoin-project** [comment]
Done :)

**Comment by paulshapiro** [comment]
Sweet!

**Pull request merged**
