### PR TITLE
Added encrypt_payment_id

### PR DESCRIPTION
**Pull request by gutenye**
It can encrypt and decrypt payment_id

cpp PR is https://github.com/mymonero/mymonero-core-cpp/pull/21

### CODE REVIEW

**Comment by paulshapiro** [comment]
@gutenye i got an error while running the tests:
```
Exception while loading module: TypeError: Module.encrypt_payment_id is not a function
    at tests ([…]/tests/MyMoneroCoreCpp.node.js:267:29)
    at […]/tests/MyMoneroCoreCpp.node.js:277:2
```

**Comment by paulshapiro** [comment]
I gotta get into the habit of checking out the source branch and testing before merging

**Comment by paulshapiro** [comment]
Oh you know what, I didn't rebuild

**Comment by paulshapiro** [comment]
Ok looks good

**Comment by gutenye** [comment]
Yep, because of the inconsistent build, it's best that you build it.

**Pull request merged**
