### PR TITLE
Added estimate_rct_tx_size

### PR DESCRIPTION
**Pull request by gutenye**
Depends on https://github.com/mymonero/mymonero-core-cpp/pull/12

### CODE REVIEW

**Comment by paulshapiro** [comment]
Hey @gutenye, could I trouble you to rebase?

**Comment by gutenye** [comment]
@paulshapiro rebased

**Comment by paulshapiro** [comment]
Would be worthwhile to add this method back to the readme now that I've removed it but I can handle that. Thanks for the PR!!

**Comment by paulshapiro** [comment]
@gutenye you're missing the estimate_rct_tx_size implementation from serial_bridge ...

**Comment by paulshapiro** [comment]
(Scratch my previous comment of course - Guten corrected me as I was looking on master and had neglected to merge develop)

**Pull request merged**
