### PR TITLE
Create tx with pre-generated txkey

### PR DESCRIPTION
**Pull request by marceloneil**
Since the tx private key is irrecoverable, I think it makes sense to provide some method of storing it. This PR adds an optional parameter to the `create_transaction()` and `construct_tx()` functions called `txkey`, so that you can generate and save the txkey, and use it to generate a transaction.

I'm unsure about how the branches work on this repo, so let me know if it's better to do a PR against `develop`

#48 against the `develop` branch

### CODE REVIEW

**Comment by paulshapiro** [comment]
Do I gather from this that you're not using SendFunds, yourself? (Just wondering why not to return txKey through SendFunds as proposed)

**Comment by marceloneil** [comment]
Oh my bad - I haven't actually used either yet, although I've relied on cryptonote_utils so far

**Comment by paulshapiro** [comment]
Though, since I'm about to merge my `cpp` branch anyway, and I'm returning tx key there (pushing soon), how about we hold off on merging this so as not to necessitate a rebase?

**Comment by paulshapiro** [comment]
@marceloneil fyi this is available now in the `cpp` branch

**Pull request closed without merging**
