### PR TITLE
Added decodeRctSimple

### PR DESCRIPTION
**Pull request by gutenye**
Depends on https://github.com/mymonero/mymonero-core-cpp/pull/11

### CODE REVIEW

**Comment by paulshapiro** [comment]
Hey @gutenye, could I trouble you to rebase? (Note we removed __bridged_fns_spec)

**Comment by gutenye** [comment]
@paulshapiro rebased

**Comment by paulshapiro** [comment]
@gutenye thank you so much!

**Comment by paulshapiro** [comment]
oh dear, just realized this was forked from master.

**Comment by paulshapiro** [comment]
Could you do another PR from `develop`? I've reverted this.

**Pull request merged**
